apiVersion: v1
kind: Service
metadata:
  name: ssa1-furniture-catalog-service
  labels:
    app: ssa1-furniture-catalog-service-deployment
spec:
  ports:
  - port: 8081
  selector:
    app: ssa1-furniture-catalog-service-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssa1-furniture-catalog-service-deployment
  name: ssa1-furniture-catalog-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ssa1-furniture-catalog-service-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ssa1-furniture-catalog-service-deployment
    spec:
      containers:
      - image: 2021mt93641/ssa1-furniture-catalog-service:1.0.0
        name: ssa1-furniture-catalog-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILE
          value: "cloud"
        
